### ISSUE TITLE
Correct Test Naming for MoreWeb

### ISSUE THREAD

**Issue by drberry85** [jstupak/FPIXUtils#44]
Hey John,

elComandante needs a new test name in the config for the different calibration tests at the different testing centers. Right now the tests are always named ElComandanteTest. It should be that when the user runs `prepareTest.py FPIXTest False` the test name should be Calibration_p17C and when the user runs `prepareTest.py FPIXTest True` the test name should be Calibration_m20C (or something like that). Also, it would be great if we could include the testing center name (FNAL or UNL) in there somehow, but seeing how this is different for the different testing sites, it's something the end user may need to control.

Doug

**Comment by jstupak** [comment]
Done
