### ISSUE TITLE
X-Ray Results placed under wrong ROC

### ISSUE THREAD

**Issue by drberry85** [jstupak/FPIXUtils#45]
Hey John,

There is an issue where if a ROC doesn't have X-Ray results. Say ROC 4 is missing, the X-Ray results on the DB will have good results for ROC 4 but no results for ROC15.
Example: http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-H-1-17

Let me know if you need the tarball,
Doug

**Comment by jstupak** [comment]
Adding @roberts42 

It looks like there is nothing that can be done from the FPIXUtils side (at least without modification of the format of the input txt file):

https://github.com/fnal/FPIXUtils/blob/master/xRayUpload.py#L57-L64

Whatever script makes this file should insert some dummy value in the txt for bad ROCS, or something like that.

**Comment by jstupak** [comment]
adding @isando3 before he creates a new issue.

@roberts42 have you had a chance to look at your code that is upstream of FPIXUtils?

**Comment by isando3** [comment]
I have added the lines in the XRayAnalysisTool that creates dummy entrances for bad rocs.
