### ISSUE TITLE
Unable to run makeSummaryPlots

### ISSUE THREAD

**Issue by jstupak** [jstupak/FPIXUtils#46]
Hey John and Jamie,

For some reason the summary plot script failed on the tests we ran today. Could it be related to the new file naming convention?

```
M-H-2-36
inputDir: /home/fnalpix1/allTestResults/M-H-2-36_FPIXTest-m20C-FNAL-160112-0950_2016-01-12_10h51m_1452617460

moduleName: M-H-2-36
WARNING: unable to run makeSummaryPlots
deadPixels: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
maskDefectPixels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
addressDefectPixels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
badBumps: [4, 2, 0, 0, 1, 4, 1, 10, 0, 0, 0, 0, 0, 5, 1, 1]
finalIana: 392.3mA
finalIdig: 471.9mA
finalTemp: -17.9
M-H-1-17
inputDir: /home/fnalpix1/allTestResults/M-H-1-17_FPIXTest-m20C-FNAL-160112-0950_2016-01-12_10h51m_1452617460
```

Doug

**Comment by lantone** [comment]
@drberry85  - please log in as yourself when you post an issue, that way you'll automatically see the responses.

Not sure about this issue, @jstupak , what piece of code generated this output?

**Comment by jstupak** [comment]
Fixed.

If we want to get these summary plots into the DB, we should run something like:

python uploadTest.py /Users/jstupak/CMS/pixel/ShareTestResults//elComandante/P-Z-2-02_ElComandanteTest_2015-12-09_09h29m_1449674997

for each of the modules.  Then manually update the DB.

**Comment by jstupak** [comment]
seems like no one cares enough to put them in the DB, so closing issue
