### ISSUE TITLE
Missing SCurves Results

### ISSUE THREAD

**Issue by drberry85** [jstupak/FPIXUtils#59]
Hey John,

You should make the uploadTest.py script not crash if the SCurves are missing (and the PreTest too, but this is lower priority). Ideally, we would like to fix pXar, but I doubt that's going to happen any time soon.

Doug

**Comment by jstupak** [comment]
Done.  Someone should update FPIXUtils on both machines

**Comment by drberry85** [comment]
Both machines are updated.
