### ISSUE TITLE
Make uploadTest.py run when missing SCurves

### ISSUE THREAD

**Issue by drberry85** [jstupak/FPIXUtils#60]
Hey John and Jamie,

We need this script to work even with the SCurves results missing. There are two lines which have problems:
https://github.com/fnal/FPIXUtils/blob/master/lessWeb.py#L749
We need to decide what to include for the untrimmable pixels when the SCurves results are missing (4160?). Maybe

```
try: VCAL_THRESH.text=str(trimDefectPixels[i])
except: VCAL_THRESH.text="4160"
```

Also produceLessWebSummaryPlot needs to run gracefully when plots are missing.
https://github.com/fnal/FPIXUtils/blob/master/moduleSummaryPlottingTools.py#L804

```
if summaryCanvas is None: return
```

Doug

**Comment by jstupak** [comment]
I think lessWeb should be fixed now

**Comment by lantone** [comment]
the second part should be fixed with da8c6494e2cc5e0bd07e1cd1a307550f77131ac7.  in principle we should rewrite that function to use existing ones, so when a protection like that gets added in the standard function, the lessweb version will automatically be protected.

**Comment by lantone** [comment]
whoops, _now_ it's fixed, with https://github.com/fnal/FPIXUtils/commit/fed0c72ea6508de14d61aad883e7e6dcec59df2b

**Comment by jstupak** [comment]
@lantone looks like we can close this now, right?

**Comment by lantone** [comment]
ah yes, i believe so
