### ISSUE TITLE
KU - Unable to upload zip file with consalidated batch request using xRayUpload from FPIXUtils

### ISSUE THREAD

**Issue by jking79** [jstupak/FPIXUtils#62]
[M-J-3-15.zip](https://github.com/fnal/FPIXUtils/files/162153/M-J-3-15.zip)

**Comment by jstupak** [comment]
Hey Jack.  Its confusing with all the different repositories.  But since you don't get an error message, this sounds to me like a pure DB issue.  You should create an issue in puhep/pudb, where it will get Greg's attention.  If he looks into it and determines its our fault, we can look into it.
