### ISSUE TITLE
KU: xRayupload.py vi consalidated batch upload did not set "number under" fields

### ISSUE THREAD

**Issue by jking79** [jstupak/FPIXUtils#64]
Just notiiced that the "number of dc under" field also did not get set when I uploaded my data.

mj421
mj315
mj130
mi126

**Comment by isando3** [comment]
Hi @jking79 
Use the latest version of the xRayUpload.py script. I just pushed the latest working version we use at UIC

**Comment by jking79** [comment]
Daniel,

I was using the latest version in FPIXUtilis….  Is this an even newer one?

Jack

**Comment by isando3** [comment]
Hi Jack,

Try using the last version I just pushed. It definitely works in our set up. 

Cheers

**Comment by jking79** [comment]
Daniel,

I will give that a shoot,

Thank You

Jack

**Comment by jking79** [comment]
Latest Version of upload script corrected this issue.
